version: "3.9"  # optional since v1.27.0
services:
  db:
    image: postgres
    restart: always
    container_name: db
    ports:
        - "${DB_PORT}:5432"
    volumes: 
      - crud:/var/lib/postgresql-static/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  adminer:
    image: adminer
    restart: always
    ports:
      - 9080:8080

volumes:
  crud:
