output   = "internal/infras/models"
wipe     = true
no-tests = true
add-enum-types = true

[psql]
  dbname = "crud"
  host   = "localhost"
  port   = 5432
  user   = "postgres"
  pass   = "postgres"
  schema = "crud"
  blacklist = ["migrations", "other"]
  sslmode = "disable"
